
DROP TABLE IF EXISTS

CREATE TABLE posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  time_stamp TEXT,
  url TEXT,
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER,
  ,
);